theme: jekyll-theme-minimal
title: 物理狗的網站
description: 
Upcoming Schedule
 - 9/1 Plus One Trio ft.葉政廷 @ BluenoteTaipei
 - 9/8 Plus One Trio ft.李世鈞 @ BluenoteTaipei
 - 9/12 YEH CHENG TING PIANO TRIO @ Jazz Spot Swing
 - 9/15 Plus One Trio ft.Michael Wang @ BluenoteTaipei
 - 9/22 Plus One Trio ft.李芳旭 @ BluenoteTaipei
 - 9/26 333 Project @ Jazz Spot Swing
#logo: [Location of the logo]
